/*
 * Copyright 2025 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.ui.specs.ChangeTests

import uk.gov.hmrc.ui.pages.{Auth, EmailVerification, Registration}
import uk.gov.hmrc.ui.specs.BaseSpec

class CheckYourAnswersSpec extends BaseSpec {

  private val registration = Registration
  private val auth         = Auth
  private val email        = EmailVerification

  Feature("Change answers for registrations via Check Your Answers") {

    Scenario("Change answers via Check Your Answers for NI Trader registration") {

      Given("the trader accesses the IOSS Registration Service")
      auth.goToAuthorityWizard()
      auth.loginUsingAuthorityWizard("100000001", "Organisation", "vatOnly", "registration")

      When("the completes a registration up to the check-your-answers page")
      registration.standardFilterQuestions()
      registration.checkJourneyUrl("confirm-vat-details")
      registration.answerVatDetailsChoice("Yes")
      registration.checkJourneyUrl("have-uk-trading-name")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("uk-trading-name/1")
      registration.enterAnswer("A trading name")
      registration.checkJourneyUrl("add-uk-trading-name")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("uk-trading-name/2")
      registration.enterAnswer("2nd name!")
      registration.checkJourneyUrl("add-uk-trading-name")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("uk-trading-name/3")
      registration.enterAnswer("Number 3")
      registration.checkJourneyUrl("add-uk-trading-name")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("previous-oss")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-country/1")
      registration.selectCountry("Hungary")
      registration.checkJourneyUrl("previous-scheme/1/1")
      registration.answerSchemeType("OSS")
      registration.checkJourneyUrl("previous-oss-scheme-number/1/1")
      registration.enterAnswer("HU11122233")
      registration.checkJourneyUrl("previous-scheme-answers/1")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-scheme/1/2")
      registration.answerSchemeType("OSS")
      registration.checkJourneyUrl("previous-oss-scheme-number/1/2")
      registration.enterAnswer("EU111222333")
      registration.checkJourneyUrl("previous-scheme-answers/1")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-scheme/1/3")
      registration.answerSchemeType("IOSS")
      registration.checkJourneyUrl("previous-ioss-scheme/1/3")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-ioss-number/1/3")
      registration.enterIossScheme("IM3487777777")
      registration.checkJourneyUrl("previous-scheme-answers/1")
      registration.continue()
      registration.checkJourneyUrl("previous-schemes-overview")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-country/2")
      registration.selectCountry("Austria")
      registration.checkJourneyUrl("previous-scheme/2/1")
      registration.answerSchemeType("OSS")
      registration.checkJourneyUrl("previous-oss-scheme-number/2/1")
      registration.enterAnswer("EU123456788")
      registration.checkJourneyUrl("previous-scheme-answers/2")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("previous-schemes-overview")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("tax-in-eu")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("eu-tax/1")
      registration.selectCountry("Romania")
      registration.checkJourneyUrl("eu-fixed-establishment/1")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("registration-tax-type/1")
      registration.selectRegistrationType("vat number")
      registration.checkJourneyUrl("eu-vat-number/1")
      registration.enterAnswer("RO1234567890")
      registration.checkJourneyUrl("eu-trading-name/1")
      registration.enterAnswer("Romanian Trading")
      registration.checkJourneyUrl("eu-fixed-establishment-address/1")
      registration.enterFixedEstablishmentAddress("1 Street Name", "", "A Town", "", "")
      registration.checkJourneyUrl("check-tax-details/1")
      registration.continue()
      registration.checkJourneyUrl("add-tax-details")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("eu-tax/2")
      registration.selectCountry("Estonia")
      registration.checkJourneyUrl("eu-fixed-establishment/2")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("registration-tax-type/2")
      registration.selectRegistrationType("tax id number")
      registration.checkJourneyUrl("eu-tax-identification-number/2")
      registration.enterAnswer("EST123987369")
      registration.checkJourneyUrl("eu-trading-name/2")
      registration.enterAnswer("Estonian Goods")
      registration.checkJourneyUrl("eu-fixed-establishment-address/2")
      registration.enterFixedEstablishmentAddress("1 Street Name", "Suburb", "A Town", "", "ES23566")
      registration.checkJourneyUrl("check-tax-details/2")
      registration.continue()
      registration.checkJourneyUrl("add-tax-details")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("website-address/1")
      registration.enterAnswer("www.first-website.com")
      registration.checkJourneyUrl("add-website-address")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("website-address/2")
      registration.enterAnswer("http://www.241goods.eu")
      registration.checkJourneyUrl("add-website-address")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("website-address/3")
      registration.enterAnswer("mywebsite.co.uk")
      registration.checkJourneyUrl("add-website-address")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("business-contact-details")
      registration.fillContactDetails("Trader Name", "07771117771", "test@testemail.com")
      email.completeEmailVerification("registration")
      registration.checkJourneyUrl("bank-account-details")
      registration.fillBankAccountDetails("Trader Name ", "ABCDEF2A", "GB33BUKB20201555555555")

      Then("the user amends and removes the trading name details they entered")
      registration.checkJourneyUrl("check-your-answers")
      registration.selectChangeOrRemoveLink(
        "add-uk-trading-name\\?waypoints\\=check-your-answers"
      )
      registration.checkJourneyUrl("add-uk-trading-name")
      registration.selectChangeOrRemoveLink(
        "uk-trading-name\\/1\\?waypoints\\=change-add-uk-trading-name\\%2Ccheck-your-answers"
      )
      registration.checkJourneyUrl("uk-trading-name/1")
      registration.enterAnswer("CYA trading name")
      registration.checkJourneyUrl("add-uk-trading-name")
      registration.selectChangeOrRemoveLink(
        "remove-uk-trading-name\\/3\\?waypoints\\=check-your-answers"
      )
      registration.checkJourneyUrl("remove-uk-trading-name/3")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("add-uk-trading-name")
      registration.answerRadioButton("no")

      Then("the user amends and removes the previous registration details they entered")
      registration.checkJourneyUrl("check-your-answers")
      registration.selectChangeOrRemoveLink(
        "previous-schemes-overview\\?waypoints\\=check-your-answers"
      )
      registration.checkJourneyUrl("previous-schemes-overview")
      registration.selectChangeOrRemoveLink(
        "remove-registration\\/1\\?waypoints\\=check-your-answers"
      )
      registration.checkJourneyUrl("remove-registration/1")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-schemes-overview")
      registration.selectChangeOrRemoveLink(
        "previous-scheme-answers\\/1\\?waypoints\\=change-previous-schemes-overview\\%2Ccheck-your-answers"
      )
      registration.checkJourneyUrl("previous-scheme-answers/1")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-scheme/1/2")
      registration.answerSchemeType("IOSS")
      registration.checkJourneyUrl("previous-ioss-scheme/1/2")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-ioss-number/1/2")
      registration.enterIossScheme("IM0407777777")
      registration.checkJourneyUrl("previous-scheme-answers/1")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("previous-schemes-overview")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-country/2")
      registration.selectCountry("Finland")
      registration.checkJourneyUrl("previous-scheme/2/1")
      registration.answerSchemeType("OSS")
      registration.checkJourneyUrl("previous-oss-scheme-number/2/1")
      registration.enterAnswer("EU222456788")
      registration.checkJourneyUrl("previous-scheme-answers/2")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("previous-schemes-overview")
      registration.answerRadioButton("no")

      Then("the user amends and removes the other registration details they entered")
      registration.checkJourneyUrl("check-your-answers")
      registration.selectChangeOrRemoveLink(
        "add-tax-details\\?waypoints\\=check-your-answers"
      )
      registration.checkJourneyUrl("add-tax-details")
      registration.selectChangeOrRemoveLink(
        "remove-tax-details\\/2\\?waypoints\\=check-your-answers"
      )
      registration.checkJourneyUrl("remove-tax-details/2")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("add-tax-details")
      registration.selectChangeOrRemoveLink(
        "check-tax-details\\/1\\?waypoints\\=change-add-tax-details\\%2Ccheck-your-answers"
      )
      registration.checkJourneyUrl("check-tax-details/1")
      registration.selectChangeOrRemoveLink(
        "eu-trading-name\\/1\\?waypoints\\=check-tax-details-1\\%2Cchange-add-tax-details\\%2Ccheck-your-answers"
      )
      registration.checkJourneyUrl("eu-trading-name/1")
      registration.enterAnswer("CYA trading name")
      registration.checkJourneyUrl("check-tax-details/1")
      registration.continue()
      registration.checkJourneyUrl("add-tax-details")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("eu-tax/2")
      registration.selectCountry("Luxembourg")
      registration.checkJourneyUrl("eu-fixed-establishment/2")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("registration-tax-type/2")
      registration.selectRegistrationType("vat number")
      registration.checkJourneyUrl("eu-vat-number/2")
      registration.enterAnswer("LU88776655")
      registration.checkJourneyUrl("eu-trading-name/2")
      registration.enterAnswer("Lux Trading")
      registration.checkJourneyUrl("eu-fixed-establishment-address/2")
      registration.enterFixedEstablishmentAddress("1 Street Name", "", "A town", "", "")
      registration.checkJourneyUrl("check-tax-details/2")
      registration.continue()
      registration.checkJourneyUrl("add-tax-details")
      registration.answerRadioButton("no")

      Then("the user amends and removes the website details they entered")
      registration.checkJourneyUrl("check-your-answers")
      registration.selectChangeOrRemoveLink(
        "add-website-address\\?waypoints\\=check-your-answers"
      )
      registration.checkJourneyUrl("add-website-address")
      registration.selectChangeOrRemoveLink("remove-website-address\\/2\\?waypoints\\=check-your-answers")
      registration.checkJourneyUrl("remove-website-address/2")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("add-website-address")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("website-address/3")
      registration.enterAnswer("www.newwebsitethree.com")
      registration.checkJourneyUrl("add-website-address")
      registration.selectChangeOrRemoveLink(
        "website-address\\/2\\?waypoints\\=change-add-website-address\\%2Ccheck-your-answers"
      )
      registration.checkJourneyUrl("website-address/2")
      registration.enterAnswer("www.websitetwo.com")
      registration.checkJourneyUrl("add-website-address")
      registration.answerRadioButton("no")

      Then("the user amends the contact details they entered")
      registration.checkJourneyUrl("check-your-answers")
      registration.selectChangeOrRemoveLink(
        "business-contact-details\\?waypoints\\=check-your-answers"
      )
      registration.checkJourneyUrl("business-contact-details")
      registration.updateField("telephoneNumber", "5555555555555")
      registration.continue()

      Then("the user amends the bank details they entered")
      registration.checkJourneyUrl("check-your-answers")
      registration.selectChangeOrRemoveLink(
        "bank-account-details\\?waypoints\\=check-your-answers"
      )
      registration.checkJourneyUrl("bank-account-details")
      registration.fillBankAccountDetails("Trader Name NI", "ABCDEF2A", "GB29NWBK60161331926819")

      And("the user successfully submits the registration on the check-your-answers page")
      registration.checkJourneyUrl("check-your-answers")
      registration.submit()
      registration.checkJourneyUrl("successful")
    }

    Scenario("Change from yes to no via Check Your Answers for NI Trader registration") {

      Given("the trader accesses the IOSS Registration Service")
      auth.goToAuthorityWizard()
      auth.loginUsingAuthorityWizard("100000001", "Organisation", "vatOnly", "registration")

      When("the completes a registration up to the check-your-answers page")
      registration.standardFilterQuestions()
      registration.checkJourneyUrl("confirm-vat-details")
      registration.answerVatDetailsChoice("Yes")
      registration.checkJourneyUrl("have-uk-trading-name")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("uk-trading-name/1")
      registration.enterAnswer("A trading name")
      registration.checkJourneyUrl("add-uk-trading-name")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("uk-trading-name/2")
      registration.enterAnswer("2nd name!")
      registration.checkJourneyUrl("add-uk-trading-name")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("uk-trading-name/3")
      registration.enterAnswer("Number 3")
      registration.checkJourneyUrl("add-uk-trading-name")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("previous-oss")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-country/1")
      registration.selectCountry("Hungary")
      registration.checkJourneyUrl("previous-scheme/1/1")
      registration.answerSchemeType("OSS")
      registration.checkJourneyUrl("previous-oss-scheme-number/1/1")
      registration.enterAnswer("HU11122233")
      registration.checkJourneyUrl("previous-scheme-answers/1")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-scheme/1/2")
      registration.answerSchemeType("OSS")
      registration.checkJourneyUrl("previous-oss-scheme-number/1/2")
      registration.enterAnswer("EU111222333")
      registration.checkJourneyUrl("previous-scheme-answers/1")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-scheme/1/3")
      registration.answerSchemeType("IOSS")
      registration.checkJourneyUrl("previous-ioss-scheme/1/3")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-ioss-number/1/3")
      registration.enterIossScheme("IM3487777777")
      registration.checkJourneyUrl("previous-scheme-answers/1")
      registration.continue()
      registration.checkJourneyUrl("previous-schemes-overview")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-country/2")
      registration.selectCountry("Austria")
      registration.checkJourneyUrl("previous-scheme/2/1")
      registration.answerSchemeType("OSS")
      registration.checkJourneyUrl("previous-oss-scheme-number/2/1")
      registration.enterAnswer("EU123456788")
      registration.checkJourneyUrl("previous-scheme-answers/2")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("previous-schemes-overview")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("tax-in-eu")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("eu-tax/1")
      registration.selectCountry("Romania")
      registration.checkJourneyUrl("eu-fixed-establishment/1")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("registration-tax-type/1")
      registration.selectRegistrationType("vat number")
      registration.checkJourneyUrl("eu-vat-number/1")
      registration.enterAnswer("RO1234567890")
      registration.checkJourneyUrl("eu-trading-name/1")
      registration.enterAnswer("Romanian Trading")
      registration.checkJourneyUrl("eu-fixed-establishment-address/1")
      registration.enterFixedEstablishmentAddress("1 Street Name", "", "A Town", "", "")
      registration.checkJourneyUrl("check-tax-details/1")
      registration.continue()
      registration.checkJourneyUrl("add-tax-details")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("eu-tax/2")
      registration.selectCountry("Estonia")
      registration.checkJourneyUrl("eu-fixed-establishment/2")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("registration-tax-type/2")
      registration.selectRegistrationType("tax id number")
      registration.checkJourneyUrl("eu-tax-identification-number/2")
      registration.enterAnswer("EST123987369")
      registration.checkJourneyUrl("eu-trading-name/2")
      registration.enterAnswer("Estonian Goods")
      registration.checkJourneyUrl("eu-fixed-establishment-address/2")
      registration.enterFixedEstablishmentAddress("1 Street Name", "Suburb", "A Town", "", "ES23566")
      registration.checkJourneyUrl("check-tax-details/2")
      registration.continue()
      registration.checkJourneyUrl("add-tax-details")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("website-address/1")
      registration.enterAnswer("www.first-website.com")
      registration.checkJourneyUrl("add-website-address")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("website-address/2")
      registration.enterAnswer("http://www.241goods.eu")
      registration.checkJourneyUrl("add-website-address")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("website-address/3")
      registration.enterAnswer("mywebsite.co.uk")
      registration.checkJourneyUrl("add-website-address")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("business-contact-details")
      registration.fillContactDetails("Trader Name", "07771117771", "test@testemail.com")
      email.completeEmailVerification("registration")
      registration.checkJourneyUrl("bank-account-details")
      registration.fillBankAccountDetails("Trader Name ", "ABCDEF2A", "GB33BUKB20201555555555")

      Then("the user changes trading name section to no")
      registration.checkJourneyUrl("check-your-answers")
      registration.selectChangeOrRemoveLink(
        "have-uk-trading-name\\?waypoints\\=check-your-answers"
      )
      registration.checkJourneyUrl("have-uk-trading-name")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("remove-all-trading-names")
      registration.answerRadioButton("yes")

      Then("the user changes previous registration section to no")
      registration.checkJourneyUrl("check-your-answers")
      registration.selectChangeOrRemoveLink(
        "previous-oss\\?waypoints\\=check-your-answers"
      )
      registration.checkJourneyUrl("previous-oss")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("remove-all-previous-registrations")
      registration.answerRadioButton("yes")

      Then("the user changes the other registration to no")
      registration.checkJourneyUrl("check-your-answers")
      registration.selectChangeOrRemoveLink(
        "tax-in-eu\\?waypoints\\=check-your-answers"
      )
      registration.checkJourneyUrl("tax-in-eu")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("remove-all-tax-details")
      registration.answerRadioButton("yes")

      And("the user successfully submits the registration on the check-your-answers page")
      registration.checkJourneyUrl("check-your-answers")
      registration.submit()
      registration.checkJourneyUrl("successful")
    }

    Scenario("Change from no to yes via Check Your Answers for NI Trader registration") {

      Given("the trader accesses the IOSS Registration Service")
      auth.goToAuthorityWizard()
      auth.loginUsingAuthorityWizard("100000001", "Organisation", "vatOnly", "registration")

      When("the completes a registration up to the check-your-answers page")
      registration.standardFilterQuestions()
      registration.checkJourneyUrl("confirm-vat-details")
      registration.answerVatDetailsChoice("Yes")
      registration.checkJourneyUrl("have-uk-trading-name")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("previous-oss")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("tax-in-eu")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("website-address/1")
      registration.enterAnswer("www.first-website.com")
      registration.checkJourneyUrl("add-website-address")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("business-contact-details")
      registration.fillContactDetails("Trader Name", "07771117771", "test@testemail.com")
      email.completeEmailVerification("registration")
      registration.checkJourneyUrl("bank-account-details")
      registration.fillBankAccountDetails("Trader Name ", "ABCDEF2A", "GB33BUKB20201555555555")

      Then("the user changes trading name section to yes and adds answers")
      registration.checkJourneyUrl("check-your-answers")
      registration.selectChangeOrRemoveLink(
        "have-uk-trading-name\\?waypoints\\=check-your-answers"
      )
      registration.checkJourneyUrl("have-uk-trading-name")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("uk-trading-name/1")
      registration.enterAnswer("A trading name")
      registration.checkJourneyUrl("add-uk-trading-name")
      registration.answerRadioButton("no")

      Then("the user changes previous registration section to yes and adds answers")
      registration.checkJourneyUrl("check-your-answers")
      registration.selectChangeOrRemoveLink(
        "previous-oss\\?waypoints\\=check-your-answers"
      )
      registration.checkJourneyUrl("previous-oss")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-country/1")
      registration.selectCountry("Hungary")
      registration.checkJourneyUrl("previous-scheme/1/1")
      registration.answerSchemeType("OSS")
      registration.checkJourneyUrl("previous-oss-scheme-number/1/1")
      registration.enterAnswer("HU11122233")
      registration.checkJourneyUrl("previous-scheme-answers/1")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("previous-schemes-overview")
      registration.answerRadioButton("no")

      Then("the user changes the other registration to yes and adds answers")
      registration.checkJourneyUrl("check-your-answers")
      registration.selectChangeOrRemoveLink(
        "tax-in-eu\\?waypoints\\=check-your-answers"
      )
      registration.checkJourneyUrl("tax-in-eu")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("eu-tax/1")
      registration.selectCountry("Romania")
      registration.checkJourneyUrl("eu-fixed-establishment/1")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("registration-tax-type/1")
      registration.selectRegistrationType("vat number")
      registration.checkJourneyUrl("eu-vat-number/1")
      registration.enterAnswer("RO1234567890")
      registration.checkJourneyUrl("eu-trading-name/1")
      registration.enterAnswer("Romanian Trading")
      registration.checkJourneyUrl("eu-fixed-establishment-address/1")
      registration.enterFixedEstablishmentAddress("1 Street Name", "", "A Town", "", "")
      registration.checkJourneyUrl("check-tax-details/1")
      registration.continue()
      registration.checkJourneyUrl("add-tax-details")
      registration.answerRadioButton("no")

      And("the user successfully submits the registration on the check-your-answers page")
      registration.checkJourneyUrl("check-your-answers")
      registration.submit()
      registration.checkJourneyUrl("successful")
    }
  }
}
